FROM python:3.11-slim-bookworm

WORKDIR /app

COPY requirements-api.txt .
RUN pip install --no-cache-dir -r requirements-api.txt

COPY master ./master

CMD ["uvicorn", "master.api:app", "--host", "0.0.0.0", "--port", "8001"]
